apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production
  
images:
  - name: 271384503138.dkr.ecr.us-east-1.amazonaws.com/auth-service
    newTag: latest
  - name: 271384503138.dkr.ecr.us-east-1.amazonaws.com/flag-service
    newTag: latest
  - name: 271384503138.dkr.ecr.us-east-1.amazonaws.com/targeting-service
    newTag: latest
  - name: 271384503138.dkr.ecr.us-east-1.amazonaws.com/evaluation-service
    newTag: latest
  - name: 271384503138.dkr.ecr.us-east-1.amazonaws.com/analytics-service
    newTag: latest

# Injeta ConfigMap dinamicamente com os endpoints da AWS gerados pelo Terraform
configMapGenerator:
  - name: togglemaster-config
    literals:
      - AWS_REGION=us-east-1
      - REDIS_HOST=togglemaster-redis.gigmz6.0001.use1.cache.amazonaws.com:6379
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/271384503138/togglemaster-events
      - DYNAMODB_TABLE=ToggleMasterAnalytics