apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: togglemaster
  namespace: flux-system

resources:
- ../../base
  
# Injeta ConfigMap dinamicamente com os endpoints da AWS gerados pelo Terraform
configMapGenerator:
- literals:
  - AWS_REGION=us-east-1
  - REDIS_HOST=togglemaster-redis.gigmz6.0001.use1.cache.amazonaws.com:6379
  - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/271384503138/togglemaster-events
  - DYNAMODB_TABLE=ToggleMasterAnalytics
  name: togglemaster-config
images:
- name: auth-service
  newName: /auth-service
  newTag: v1.0.0-ea4b5a404540552abba0b8a2f598bd5ffbc6acf6
