apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: togglemaster
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Utiliza a role/IRSA associada aos nós ou ao service account
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa