apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: togglemaster-eks-cluster
  region: us-east-1 # Altere para a região onde você criou sua VPC

# Configuração para reutilizar a sua VPC e Subnets existentes
vpc:
  id: "vpc-00d83f052c98e2ae6" # ex: vpc-0123456789abcdef0
  subnets:
    private:
      us-east-1a: { id: "subnet-0807d6f3266985b35" }
      us-east-1b: { id: "subnet-0e09cd4012d1a2925" }

# Definição dos nós EC2 (Workers) que rodarão seus microsserviços
managedNodeGroups:
  - name: togglemaster-ng
    instanceType: t3.medium # Instância excelente custo-benefício para conta pessoal
    desiredCapacity: 2      # Começa com 2 instâncias EC2
    minSize: 1
    maxSize: 4
    privateNetworking: true # Garante que as EC2 fiquem isoladas nas subnets privadas
    securityGroups:
      attachIDs: ["sg-00a5db29345cf70bc"] # Vincula o Security Group que você criou
    
    # Gerenciamento Automático de Permissões IAM na sua conta pessoal
    iam:
      withAddonPolicies:
        imageBuilder: true # Dá permissão automática de leitura/pull ao seu Amazon ECR!
        albIngress: true   # Permissão para o Ingress Controller criar o Load Balancer