apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  REDIS_URL: "redis://togglemaster-redis.gigmz6.ng.0001.use1.cache.amazonaws.com:6379"
  REDIS_PORT: "6379"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/271384503138/togglemaster-events"
  AWS_REGION: "us-east-1"
  PORT: "8004"