apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: togglemaster
data:
  DB_HOST_AUTH: "togglemaster-rds-auth.cazcgm4ikzel.us-east-1.rds.amazonaws.com"
  DB_PORT_AUTH: "5432"
  DB_NAME_AUTH: "postgres"
  PORT_AUTH: "8001" # Alterado para 8001 para bater com o containerPort e probes