apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-externalsecret
  namespace: togglemaster
spec:
  refreshInterval: 1h # Polling a cada 1 hora para atualizar caso a senha mude na AWS
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: targeting-service-secret # Nome da secret que o pod consome
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: togglemaster/targeting-service # Nome exato da secret no Secrets Manager